logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
server:
  port: 53253
spring:
  application:
    name: microservice-3
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: messageConfig
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            type-mapping: MessageDto:com.example.microservice3.dto.MessageDto
            trusted:
              packages: 'MessageDto:com.example.microservice3.dto.MessageDto'