logging:
    pattern:
        console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
server:
    port: 53252
spring:
    application:
        name: microservice-2
    kafka:
        consumer:
            properties:
                spring:
                    json:
                        trusted:
                            packages: '*'
